### ISSUE TITLE
Add contributors

### ISSUE THREAD

**Issue by LCObus** [chanzuckerberg/napari-segmentation-workshop#20]
to highlight the bravo cohort members and their contributions, we should be sure to include a page dedicated to them and their profiles/links.

**Comment by tdimino** [comment]
We could have a "Notable contributors" page under "Preface" that includes:

- Group photo of the Bravo Cohort.
- Short paragraph of copy about how we collaborated together.
- Links to individual bio pages for each imaging scientist.

**Comment by LCObus** [comment]
@tdimino could you take this on and add? we have their photos from the decks, but should double check with each to ensure they have no reservations about individual pages and/or links.

**Comment by tdimino** [comment]
Sure, I'll start building the central page and reach out to each of them
about their individual contributor page.

**Comment by tdimino** [comment]
https://chanzuckerberg.github.io/napari-segmentation-workshop/preface/whomadethis.html#contributors-to-course

Contributors have been added, but additional links may be provided for each person. And although they have bylines on lessons they authored, it may make sense to link to those lessons from this page as well. 

Photos also need to be standardized in size. Jupyter Book makes this complicated, so it may be easier to crop each one to the same dimensions.
