### ISSUE TITLE
Add additional copy to preface 

### ISSUE THREAD

**Issue by LCObus** [chanzuckerberg/napari-segmentation-workshop#21]
https://chanzuckerberg.github.io/napari-segmentation-workshop/preface/landing.html

In the spirit of transparency, we should include more context on why we decided on the bravo cohort and its goals to fill outstanding needs in the napari community, as well as process. can pull from existing copy in deck.

**Comment by tdimino** [comment]
The following page's URL has been renamed:

https://chanzuckerberg.github.io/napari-segmentation-workshop/preface/whomadethis.html
