### ISSUE TITLE
combine "overview" with stage bold link

### ISSUE THREAD

**Issue by LCObus** [chanzuckerberg/napari-segmentation-workshop#23]
is it possible to make the sections like "STAGE I: ONBOARDING TO NAPARI" clickable and add the overview content there? feels more intuitive. overview also implies wholistic goals, so i think a sentence explaining what you expect to learn across all the lessons would be valuable.

**Comment by tdimino** [comment]
I had wanted to make the stage names clickable, but AFAIK it's not possible with Jupyter Book's default styling. I looked for examples of this on other books and saw that they each adopted something akin to an "Overview" page to get around this.
