### ISSUE TITLE
"overview of first stage/final stage" not intuitive

### ISSUE THREAD

**Issue by LCObus** [chanzuckerberg/napari-segmentation-workshop#27]
i would edit to "overview" - first and final stage don't have much meaning when there are two sections that dont necessarily have to be operated sequentionally. I would also recommend to change "background on course" in preface section- maybe to "Acknowledgements and Contributors"? we should discuss.

**Comment by tdimino** [comment]
Deleted the overview pages from the TOC. All the [content requests](https://github.com/chanzuckerberg/napari-segmentation-workshop/issues/25) for those pages still stand if you were to resurrect them, but for the MVP I don't think they're crucial.
