### ISSUE TITLE
github links in book send to 404

### ISSUE THREAD

**Issue by LCObus** [chanzuckerberg/napari-segmentation-workshop#34]
<img width="339" alt="Screen Shot 2022-06-09 at 1 59 53 PM" src="https://user-images.githubusercontent.com/63607867/172944061-5e4ed8c6-065a-472f-be5a-017102454753.png">

links to open the repo and file an issue from the notebook both send to 404 sites: https://github.com/chanzuckerberg/napari%20Segmentation%20Course

did we rename the url?

**Comment by tdimino** [comment]
Github link now works from main page of the site.
